Repository xgeekshq/js-intl-kitchen-sink, pull requests merged in 2019-10, with the labels that each got.

#26 Twitter share icon v1
  src/components/Header/index.js
  src/components/Header/styles.module.css
Labels: Author: waiting changes, Author: waiting feedback

#52 add alt for Avatar and add tab focus outline
  src/components/Layout/index.js
  src/components/Layout/styles.module.css
  src/components/Sidebar/index.js
  src/components/Sidebar/styles.module.css
  src/index.css
  src/pages/DateTimeFormat/index.js
  src/pages/Home/index.js
Labels: Author: waiting feedback

#64 Add data and forms to relative time
  CONTRIBUTING.md
  src/data/locales.js
  src/data/options.js
  src/data/usefulLinks.js
  src/pages/DateTimeFormat/index.js
  src/pages/RelativeTimeFormat/actions.js
  src/pages/RelativeTimeFormat/constants.js
  src/pages/RelativeTimeFormat/index.js
  src/pages/RelativeTimeFormat/reducer.js
  src/utils/index.js
Labels: Author: waiting changes
